import "/styles/style.css"
import "/styles/components/header.css"
import "/styles/components/mobileMenu.css"
import "/styles/components/hero.css"
import "/styles/components/sponsors.css"
import "/styles/components/about.css"
import "/styles/components/gallery.css"
import "/styles/components/services.css"
import "/styles/components/cta.css"
import "/styles/components/contact.css"
import "/styles/components/footer.css"
import "/styles/utility.css"

import "/src/features"